### ISSUE TITLE
Documentation feedback

### ISSUE THREAD

**Issue by MoElkhidir** [pufflyai/prompt-studio-docs#7]
1. https://github.com/pufflyai/prompt-studio-docs/blob/1be524bf4aafd6e17f3939549950b215a5f2ca82/docs/concepts/sets.md?plain=1#L9 -> "file" can be replaced with "a list of files"

2. https://github.com/pufflyai/prompt-studio-docs/blob/1be524bf4aafd6e17f3939549950b215a5f2ca82/docs/concepts/sets.md?plain=1#L46 -> I think the example should be moved here and a link to the set of files example should be put in the files doc

3. 
<img width="292" alt="image" src="https://user-images.githubusercontent.com/9537579/230957001-d5aadcf6-f516-4948-98ea-a48bd884c925.png">
-> I have seen this in multiple page, as a user, I don't think I need to see this

4. https://github.com/pufflyai/prompt-studio-docs/blob/1be524bf4aafd6e17f3939549950b215a5f2ca82/docs/concepts/concepts.md?plain=1#L19 
-> is a `set` defined as a `Set` in Java? where no duplicates  values is allowed? Generally I find the names of `set` and `collection` might be a bit confusing, is there a way to rename either of them to be more descriptive?

5. https://github.com/pufflyai/prompt-studio-docs/blob/1be524bf4aafd6e17f3939549950b215a5f2ca82/docs/intro.md?plain=1#L50 -> This is an external link, should be in a different section for external links?

**Comment by SaraFatih** [comment]
Thank you so much Mo! I just updated the documentation accordingly.
